# for local dev env setup
# docker compose -p hands-on-lab -f docker-compose.yaml up -d
# docker compose -p hands-on-lab -f docker-compose.yaml down
services:
  springboot:
    image: nanachi1027/springboot-micrometer-hol:latest
    container_name: hands-on-spring-app
    ports:
      - "8080:8080"
    networks:
      - hands-on-network

  prometheus:
    image: prom/prometheus:latest
    container_name: hands-on-prometheus
    ports:
      - "31000:9090"   # host port 31000 → container port 9090
    volumes:
      - hands-on-prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules
    restart: unless-stopped
    networks:
      - hands-on-network

  grafana:
    image: grafana/grafana:latest
    container_name: hands-on-grafana
    ports:
      - "32000:3000"   # host port 32000 → container port 3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - hands-on-grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - hands-on-network

volumes:
  hands-on-prometheus-data:
  hands-on-grafana-data:

networks:
  hands-on-network: