# for local dev env setup
#  docker compose -p hands-on-lab -f docker-compose.yaml up -d
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: hands-on_prometheus
    ports:
      - "31000:9090"   # host port 31000 → container port 9090
    volumes:
      - hands-on-lab_prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - hands-on-lab_spring-micrometer

  grafana:
    image: grafana/grafana:latest
    container_name: hands-on_grafana
    ports:
      - "32000:3000"   # host port 32000 → container port 3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - hands-on-lab_grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - hands-on-lab_spring-micrometer

volumes:
  hands-on-lab_prometheus_data:
  hands-on-lab_grafana_data:

networks:
  hands-on-lab_spring-micrometer: