server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: springboot-micrometer-hol

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true