apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: hands-on-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards/json
            - name: grafana-dashboard-config
              mountPath: /etc/grafana/provisioning/dashboards/
      volumes:
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
        - name: grafana-dashboard-config
          configMap:
            name: grafana-dashboard-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: hands-on-lab
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000