apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: hands-on-lab
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s   # How often metrics are scraped
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'springboot-app'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['hands-on-spring-app:8080']  # Spring Boot app running in cluster

      - job_name: 'custom-metrics'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['hands-on-spring-app:8080']
        relabel_configs:
          - source_labels: [__name__]
            regex: 'custom_.*'
            action: keep

    rule_files:
      - "/etc/prometheus/rules/*.yml"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: hands-on-lab
data:
  custom-rules.yml: |
    groups:
      - name: actuator_metrics
        interval: 30s
        rules:
          - record: http_server_requests_total
            expr: sum by (method, status, uri) (http_server_requests_seconds_count)
            labels:
              source: actuator
          - record: http_server_request_duration_seconds_avg
            expr: sum by (method, status, uri) (http_server_requests_seconds_sum)
              / sum by (method, status, uri) (http_server_requests_seconds_count)
            labels:
              source: actuator

      - name: aop_service_layer_metrics
        interval: 30s
        rules:
          - record: foo_service_method_duration_avg
            expr: sum by (method) (foo_service_methods_sum)
              / sum by (method) (foo_service_methods_count)
            labels:
              source: aop

          - record: foo_service_methods_total
            expr: sum by (method) (foo_service_calls)
            labels:
              source: aop

          - alert: FooServiceMethodSlow
            expr: foo_service_method_duration_avg > 1
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "FooService method avg duration > 1s"

      - name: interceptor_servlet_layer_metrics
        interval: 30s
        rules:
          - record: http_request_duration_avg
            expr: sum by (method, uri) (http_request_duration_seconds_sum)
              / sum by (method, uri) (http_request_duration_seconds_count)
            labels:
              source: interceptor

          - record: http_request_total
            expr: sum by (method, uri) (http_request_duration_seconds_count)
            labels:
              source: interceptor

          - alert: HighHttpRequestLatency
            expr: http_request_duration_avg > 1
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "HTTP request avg duration > 1s"