global:
  scrape_interval: 5s   # How often metrics are scraped
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'springboot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Spring Boot app running on host

  # Optional: custom metrics job
  - job_name: 'custom-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    relabel_configs:
      # Example: keep only metrics starting with "custom_"
      - source_labels: [__name__]
        regex: 'custom_.*'
        action: keep